# Kustomization do módulo cert-manager.
# Aplique APENAS depois que o cert-manager (Deployment+CRDs) estiver no ar.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: <YOUR-ORGANIZATION-HERE>

resources:
  - namespace.yaml
  - clusterissuer-prod.yaml
  - clusterissuer-staging.yaml
