apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: <YOUR-ORGANIZATION-HERE>

resources:
  - pvc.yaml
  - secret.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
