apiVersion: v1
kind: Service
metadata:
  name: n8n-webhook
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: <YOUR-ORGANIZATION-HERE>
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: webhook
  ports:
    - name: http
      port: 5678
      targetPort: http
      protocol: TCP
